name: ricco-dev
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
dependencies:
  - appdirs=1.4.3=py_1
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=19.3.0=py_0
  - black=19.10b0=py38_0
  - boost-cpp=1.72.0=h2ba7cf6_1
  - brotlipy=0.7.0=py38h1e8a9f7_1000
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.0=py38ha419a9e_0
  - cfgv=3.1.0=py_0
  - cfitsio=3.470=he774522_5
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - codecov=2.1.7=pyh9f0ad1d_0
  - colorama=0.4.3=py_0
  - coverage=5.1=py38h1e8a9f7_0
  - cryptography=2.9.2=py38hba49e27_0
  - curl=7.71.0=h4b64cdc_0
  - cycler=0.10.0=py_2
  - descartes=1.1.0=py_4
  - distlib=0.3.1=pyh9f0ad1d_0
  - editdistance=0.5.3=py38hb99c5c2_0
  - expat=2.2.9=he025d50_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - fiona=1.8.13=py38h41bf4fa_1
  - freetype=2.10.2=hd328e21_0
  - freexl=1.0.5=hd288d7e_1002
  - gdal=3.0.4=py38h3ba59e7_9
  - geographiclib=1.50=py_0
  - geopy=2.0.0=pyh9f0ad1d_0
  - geos=3.8.1=he025d50_0
  - geotiff=1.5.1=h3d29ae3_10
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.65.0=he4de6d7_0
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.6=nompi_ha405e13_100
  - icu=64.2=he025d50_1
  - identify=1.4.20=pyh9f0ad1d_0
  - idna=2.10=pyh9f0ad1d_0
  - jpeg=9d=he774522_0
  - kealib=1.4.13=h3b59ab9_1
  - kiwisolver=1.2.0=py38heaebd3c_0
  - krb5=1.17.1=hc04afaa_1
  - libblas=3.8.0=8_h8933c1f_netlib
  - libcblas=3.8.0=8_h8933c1f_netlib
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.71.0=h4b64cdc_0
  - libffi=3.2.1=h6538335_1007
  - libgdal=3.0.4=h6f60a84_9
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h7e985d0_1011
  - liblapack=3.8.0=8_h8933c1f_netlib
  - libnetcdf=4.7.4=nompi_h256d12c_104
  - libpng=1.6.37=hfe6a214_1
  - libpq=12.2=hd9aa61d_1
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=h51df0ed_1038
  - libssh2=1.9.0=h3235a2c_2
  - libtiff=4.1.0=h885aae3_6
  - libwebp-base=1.1.0=hfa6e2cd_3
  - libxml2=2.9.10=h5d81f1c_1
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py38h1626042_0
  - mock=4.0.2=py38h32f6830_0
  - more-itertools=8.4.0=py_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py38h32f6830_1
  - nodeenv=1.4.0=pyh9f0ad1d_0
  - numpy=1.18.5=py38h72c728b_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1g=he774522_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py38he6e81aa_0
  - pathspec=0.8.0=pyh9f0ad1d_0
  - pcre=8.44=h6538335_0
  - pip=20.1.1=py_1
  - pluggy=0.13.1=py38h32f6830_2
  - poppler=0.87.0=h0cd1227_1
  - poppler-data=0.4.9=1
  - postgresql=12.2=he14cc48_1
  - pre-commit=2.5.1=py38h32f6830_0
  - proj=7.0.0=haa36216_3
  - psycopg2=2.8.5=py38hba49e27_1
  - py=1.9.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38h1dd9442_0
  - pyqt=5.12.3=py38h7ae7562_3
  - pysocks=1.7.1=py38h32f6830_1
  - pytest=5.4.3=py38h32f6830_0
  - pytest-cov=2.10.0=pyh9f0ad1d_0
  - python=3.8.3=cpython_h5fd99cc_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py38h9de7a3e_0
  - qt=5.12.5=h7ef1ec2_0
  - regex=2020.6.8=py38h1e8a9f7_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rtree=0.9.4=py38h7ad75cc_1
  - setuptools=47.3.1=py38h32f6830_0
  - shapely=1.7.0=py38hbf43935_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlalchemy=1.3.18=py38h1e8a9f7_0
  - sqlite=3.32.3=he774522_0
  - tbb=2020.1=he980bc4_0
  - tiledb=1.7.7=h0b90766_3
  - tk=8.6.10=hfa6e2cd_0
  - toml=0.10.1=pyh9f0ad1d_0
  - tornado=6.0.4=py38hfa6e2cd_0
  - typed-ast=1.4.1=py38hfa6e2cd_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - virtualenv=20.0.20=py38h32f6830_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_1003
  - xerces-c=3.2.2=h6538335_1004
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.5=he774522_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=h9f78265_3
  - pip:
    - geojson==2.5.0
    - geopandas==0.8.0
    - pypinyin==0.38.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - ricco==0.1.5
    - tqdm==4.47.0
prefix: C:\ProgramData\Anaconda3\envs\ricco-dev

